
server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogo_filmes?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: hoot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true